apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mine
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: sahandha/lsstscheduler
            args:
            - /bin/sh
            - -c
            - python /sched.py; ls; echo hello
          restartPolicy: OnFailure
