kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: resourceallocation
spec:
  selector:
    component: resourceallocation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 27017
