kind: Deployment
apiVersion: apps/v1
metadata:
  name: lsstsched
  namespace: resourceallocation
  labels:
    app: lsstsched
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsstsched
  template:
    metadata:
      labels:
        app: lsstsched
    spec:
      containers:
      - name: lsstsched
        image: sahandha/lsstscheduler
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
